import fetch from 'node-fetch'; // Wait! Does node-fetch exist in dependencies? Let's use native fetch which is built-in to Node 18+.

async function runTest() {
  const baseUrl = 'http://localhost:5000/api';
  console.log('--- Testing API Flow ---');

  let token = '';
  const testEmail = `test_${Date.now()}@gmail.com`;

  // 1. Try Registering
  try {
    console.log(`Registering user with email: ${testEmail}...`);
    const regRes = await fetch(`${baseUrl}/auth/register`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: 'Hemanth Test',
        email: testEmail,
        password: 'password123'
      })
    });
    const regData = await regRes.json();
    if (regRes.ok) {
      console.log('Registration successful!');
      token = regData.token;
    } else {
      console.log('Registration failed:', regData.error);
      
      // 2. Try Logging in instead
      console.log('Logging in user...');
      const loginRes = await fetch(`${baseUrl}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: testEmail,
          password: 'password123'
        })
      });
      const loginData = await loginRes.json();
      if (loginRes.ok) {
        console.log('Login successful!');
        token = loginData.token;
      } else {
        throw new Error(`Login failed: ${loginData.error}`);
      }
    }
  } catch (err) {
    console.error('Auth check failed:', err.message);
    process.exit(1);
  }

  // 3. Try generating a trip
  try {
    console.log('Generating trip plan for Tokyo, Japan...');
    const tripRes = await fetch(`${baseUrl}/trips`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({
        destination: 'Tokyo, Japan',
        durationDays: 5,
        budgetTier: 'Medium',
        interests: ['Adventure', 'Culture', 'Food & Cuisine', 'Nature']
      })
    });

    const tripData = await tripRes.json();
    if (tripRes.ok) {
      console.log('Trip successfully generated by AI!');
      console.log('Trip ID:', tripData.data._id);
      console.log('Destination:', tripData.data.destination);
      console.log('Duration:', tripData.data.durationDays, 'days');
      console.log('Hotels suggested:', tripData.data.hotels.map(h => `${h.name} (${h.tier})`).join(', '));
      console.log('Total Estimated Budget:', tripData.data.estimatedBudget.total, 'USD');
      console.log('Packing categories:', tripData.data.packingList.map(p => p.category).join(', '));
      console.log('--- TEST SUCCESSFUL ---');
    } else {
      throw new Error(`Trip generation failed: ${tripData.error}`);
    }
  } catch (err) {
    console.error('Trip generation check failed:', err.message);
    process.exit(1);
  }
}

runTest();
